### PR TITLE
Fix invalid area size when gap is negative

### PR DESCRIPTION
**Pull request by daohoangson**
I'm trying to make a table-like layout in Flutter so I have to use negative gap to accommodate outside and inside borders. The code looks like this:

```dart
        Stack(
          children: <Widget>[
            LayoutGrid(
              columnGap: -borderWidth,
              rowGap: -borderWidth,
              gridFit: GridFit.passthrough,
              templateColumnSizes: [/* ... */],
              templateRowSizes: [/* IntrinsicContentTrackSize()... */],
              children: [
                Container(
                  child: cell,
                  decoration: BoxDecoration(border: Border.all(width: borderWidth)
                ),
                /* ... */
              ],
            ),
            Positioned.fill(
              child: Container(decoration: BoxDecoration(border: Border.all(width: borderWidth))
            ),
          ],
        )
``` 

This PR tries to fix the invalid area size when the rows are `IntrinsicContentTrackSize`s. I have also included a golden image so it's easier to imagine.

### CODE REVIEW

**Comment by shyndman** [comment]
Hi @daohoangson,

I'm sorry, I've been in a bad email situation recently and I missed this PR. Give me a couple days to look at it.

**Comment by daohoangson** [comment]
Ah, I should have had tagged you after a few days without response. Thanks for taking a look now.

**Comment by daohoangson** [comment]
Sorry for bugging you @shyndman. Have you had the chance to review this?

**Comment by theneshofficial** [comment]
Hi @shyndman any progress on this PR?

**Comment by shyndman** [comment]
I'm sorry @theneshofficial, work has been busy and I've been shirking my duties.

I initially had trepidations about this change because it differs from the CSS grid layout spec, near as I can tell, and I didn't 

1. have the time to think about it deeply 
2. want to get into undefined behavior land

Upon reflection, the change is so minimal, and seems protective of varying input...so I think it's great. Thanks for your contribution. I'll be quicker next time.

**Comment by shyndman** [comment]
aaaaaaaand, published

**Comment by daohoangson** [comment]
Awesome, thank you very much @shyndman

**Pull request merged**
